-- Criar tabela unificada de pessoas
CREATE TABLE public.pessoa (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  codigo INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nome TEXT NOT NULL,
  email TEXT,
  nivel TEXT DEFAULT 'N1',
  setor_id UUID REFERENCES public.area_documento(id),
  user_id UUID UNIQUE,
  deve_alterar_senha BOOLEAN DEFAULT false,
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public.pessoa ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
CREATE POLICY "Authenticated users can view pessoa"
ON public.pessoa FOR SELECT
USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert pessoa"
ON public.pessoa FOR INSERT
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update pessoa"
ON public.pessoa FOR UPDATE
USING (auth.role() = 'authenticated');

CREATE POLICY "Admins can delete pessoa"
ON public.pessoa FOR DELETE
USING (has_role(auth.uid(), 'administrador'));

-- Migrar dados existentes de prestador_servico para pessoa
INSERT INTO public.pessoa (nome, email, nivel, setor_id, ativo, created_at, updated_at)
SELECT nome, email, nivel, setor_id, true, created_at, updated_at
FROM public.prestador_servico;

-- Migrar dados existentes de profiles para pessoa (apenas se não existir email duplicado)
INSERT INTO public.pessoa (nome, email, user_id, deve_alterar_senha, ativo, created_at, updated_at)
SELECT p.nome, p.email, p.user_id, p.deve_alterar_senha, true, p.created_at, p.updated_at
FROM public.profiles p
WHERE NOT EXISTS (
  SELECT 1 FROM public.pessoa pe WHERE pe.email = p.email AND p.email IS NOT NULL
);